### PR TITLE
feat: Implement Bitwise and Shift Operator Support

### PR DESCRIPTION
**Pull request by ckganesan**
This PR introduces support for bitwise and shift operators. With this enhancement, users can now perform advanced bitwise operations, including AND, OR, XOR, and NOT, as well as left and right shift operations.

```
&    bitwise AND            integers
// To manage bitwise OR operations and various callbacks (predicates, built-ins, and custom functions)
|    bitwise OR             integers
// Duplicate the Caret operator to prevent confusion with the Exponent operator.
^^    bitwise XOR           integers
&^   bit clear (AND NOT)    integers

<<   left shift             integer << integer >= 0
>>   right shift            integer >> integer >= 0
```

Ref: #207

### CODE REVIEW

**Comment by antonmedv** [comment]
Let’s not override pipe operator. This will create confusion. Also ^^ is really odd. 

What about using full names as operators for bitwise ops?

I already know a good one:

- xor


    A xor B

We just need to find nice ones for other. I know some languages do that.

**Comment by antonmedv** [comment]
And let’s implement them as functions. So we don’t need to worry about precedence.

**Comment by antonmedv** [comment]
Or as alternative solution add a special "macro": `bit` which will be converting those expressions:

```js
bit(A | B ^ ~C) 
```

**Comment by ckganesan** [comment]
> And let’s implement them as functions. So we don’t need to worry about precedence.

Following the comments, I will also be adding the following built-in functions, along with their respective precedences.

```
// Bitwise ops
&, bitand     -    bitwise AND            integers
bor, bitor    -    bitwise OR             integers
xor, bitxor   -    bitwise XOR            integers
&^, bitnand   -    bit clear (AND NOT)    integers
~, bitnot     -    bit NOT                integer

// Bit Shift ops
<<, bitshl    -    left shift             integer << integer >= 0
>>, bitshr    -    right shift            integer >> integer >= 0
>>>, bitushr  -    unsigned right shift 
```

**Comment by antonmedv** [comment]
But let's drop operators

**Pull request merged**
