### PR TITLE
Enhanced min and max built-in functions to Support Arrays of Integers and Floats

### PR DESCRIPTION
**Pull request by ckganesan**
Enhanced support for array inputs in the min and max built-in functions, now accommodating arrays of integers and floats. This update extends the functionality to handle diverse data types seamlessly, improving the flexibility and usability of the functions. #574

### CODE REVIEW

**Comment by antonmedv** [comment]
Cool! What about adding support for this as well?

```
max([1, 2, 3], 10) // output 10
```

**Comment by antonmedv** [comment]
But I think it will complicate things. We can add `flatten()` builtin.

**Comment by ckganesan** [comment]
> Cool! What about adding support for this as well?
> 
> ```
> max([1, 2, 3], 10) // output 10
> ```

Certainly, I can include that as well if you'd like.

**Review by antonmedv — APPROVED** [review]

**Comment by antonmedv** [comment]
BTW, lets add this to https://expr-lang.org/docs/language-definition#mean and https://expr-lang.org/docs/language-definition#mean as well

**Comment by PranavPeshwe** [comment]
Would be good to include some negative numbers in the tests.

**Pull request merged**
