### PR TITLE
Incorporate support for raw string literals

### PR DESCRIPTION
**Pull request by ckganesan**
The current parser lacks support for raw string literals

### CODE REVIEW

**Comment by antonmedv** [comment]
Nice! But I'm thinking about adding byte strings later as well.
 
    b'bytes string'

So maybe it is better to add raw strings was a prefix?

    r'raw string\n'
    r"any quotes"
    r`and those too`

But allow back quotas to be multi line?

    r`nice
    multi
    line`

**Comment by ckganesan** [comment]
I suggest that the `r` prefix be reserved specifically for raw strings enclosed in single (`' '`) or double quotes (`" "`), as this approach clearly distinguishes between standard and raw strings. For raw strings without any prefix, we can utilize backticks (``)

**Comment by ckganesan** [comment]
If you aim to implement raw strings with the `r` prefix for both single (`' '`) and double quotes (`" "`). I will take on this task and submit a pull request within the same PR.

**Comment by antonmedv** [comment]
> I recommend that we reserve the r prefix exclusively for raw strings enclosed in single (' ') or double quotes (" "), aligning with your previous comment for a clear distinction between standard and raw strings. Additionally, for raw strings that do not require a prefix, using backticks (``) would be an effective approach.

What is reason?

**Comment by ckganesan** [comment]
> > I recommend that we reserve the r prefix exclusively for raw strings enclosed in single (' ') or double quotes (" "), aligning with your previous comment for a clear distinction between standard and raw strings. Additionally, for raw strings that do not require a prefix, using backticks (``) would be an effective approach.
> 
> What is reason?

Backticks are inherently interpreted as raw strings, which means there's no need to use escape sequences. However, when using quotes to implement raw strings, escape sequences become essential.

**Comment by ckganesan** [comment]
That's why I believe there is no need for the `r` prefix when using backtick symbols alone.

**Comment by antonmedv** [comment]
I see. This makes good point. 

I was thinking about how raw string implemented in python.

**Comment by ckganesan** [comment]
While Python uses the r prefix for raw strings, Go achieves this using backtick symbols.

```go
// Go Using backticks for raw string
rawString := `This is a raw string in Go.
It can span multiple lines and include "quotes" without escaping them.`
```

```python
# python Using the 'r' prefix for raw string
raw_string = r"This is a raw string in Python.\nIt can include escape characters like \n, \t, etc., without any special effect."
```

We can achieve raw strings in two ways: using the r prefix or with backticks

**Comment by antonmedv** [comment]
Ok. Let me review pr more carefully.

**Review by antonmedv — APPROVED** [review]

**Pull request merged**
